version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cash:/data
    container_name: redis

  fastapi:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    container_name: fasapi
    command: sh -c "python main.py"

volumes:
  postgres_data:
    driver: local
  cash:
    driver: local